recipes:
  - cookbooks/homebrew/default.rb
  - cookbooks/git/default.rb
  - cookbooks/go/default.rb
  - cookbooks/bash/default.rb
  - cookbooks/direnv/default.rb
  - cookbooks/cmake/default.rb
  - cookbooks/zsh/default.rb
  - cookbooks/gpg/default.rb
  - cookbooks/awscli/default.rb
  - cookbooks/peco/default.rb
  - cookbooks/ghq/default.rb
  - cookbooks/docker/default.rb
