recipes:
  - cookbooks/homebrew/default.rb
  - cookbooks/git/default.rb
  - cookbooks/go/default.rb
  - cookbooks/visual-studio-code/default.rb
  - cookbooks/bash/default.rb
  - cookbooks/plenv/default.rb
  - cookbooks/rbenv/default.rb
  - cookbooks/pyenv/default.rb
  - cookbooks/gpg/default.rb
  - cookbooks/ghostscript/default.rb
  - cookbooks/imagemagick/default.rb
  - cookbooks/direnv/default.rb
  - cookbooks/cmake/default.rb
